apiVersion: v2
name: logging-stack
description: A lightweight logging stack with Fluent Bit, Loki, and Grafana
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: fluent-bit
    version: "0.46.7"
    repository: "https://fluent.github.io/helm-charts"
  - name: loki
    version: "6.15.5"
    repository: "https://grafana.github.io/helm-charts"
  - name: grafana
    version: "8.3.5"
    repository: "https://grafana.github.io/helm-charts"
