name: Release Helm Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Build dependencies
        run: |
          cd monitoring-stack
          helm dependency update

      - name: Package chart
        run: |
          helm package monitoring-stack

      - name: Generate index.yaml
        run: |
          helm repo index . --url https://alexiscarbillet.github.io/my-helm-charts

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
